# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Codata
tagline:             'Coding the data'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 
baseurl:             '/codata'
paginate:            2
plugins:             [jekyll-paginate]
# markdown:            redcarpet   # not surported any more
exclude:             ['README.html']
# paginate_path:       'page:num'

# About/contact
author:
  name:              Hongyu Guo

# Custom vars
version:             1.0

